"""Streamlit local trial app for the FedEx IP freight checker.

It reuses processed CSV files generated by:
    python3 scripts/01_extract_ip_data.py
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data_processed"

TOOL_VERSION = "2026-05-17"
IP_RATE_EFFECTIVE_DATE = "2026-01-05"
DEMAND_EFFECTIVE_DATE = "2026-04-13"
FEDEX_FUEL_SOURCE_URL = "https://www.fedex.com/zh-cn/shipping/surcharges.html"
FEDEX_FUEL_TABLE_URL = "https://www.fedex.com/content/dam/fedex/international/rates/fedex-fuel-table-may-2026-apac.pdf"
FEDEX_FUEL_EFFECTIVE_LABEL = "2026-04-06 至 2026-05-17"
FEDEX_FUEL_RATE = 0.48
FUEL_BUFFER_RATE = 0.05
DEFAULT_FUEL_RATE = FEDEX_FUEL_RATE + FUEL_BUFFER_RATE
DEFAULT_MARKUP = 1.1
DEFAULT_EXCHANGE_RATE = 6.8


@st.cache_data
def load_data():
    aliases = pd.read_csv(DATA_DIR / "country_alias.csv")
    fixed = pd.read_csv(DATA_DIR / "ip_parcel_rate_0_20_5kg.csv")
    per_kg = pd.read_csv(DATA_DIR / "ip_parcel_rate_21kg_plus.csv")
    dropdown = (
        aliases[aliases["match_note"].eq("Dropdown display label")]["alias"]
        .dropna()
        .drop_duplicates()
        .sort_values(key=lambda s: s.str.lower())
        .tolist()
    )
    return aliases, fixed, per_kg, dropdown


def lookup_country(country_input: str, aliases: pd.DataFrame):
    key = country_input.strip().lower()
    matched = aliases[aliases["alias_normalized"] == key]
    if matched.empty:
        return None
    return matched.iloc[0]


def find_dropdown_index(country_input: str, aliases: pd.DataFrame, dropdown: list[str]) -> int | None:
    query = country_input.strip().lower()
    if not query:
        return None

    for idx, label in enumerate(dropdown):
        if query in label.lower():
            return idx

    matched = lookup_country(country_input, aliases)
    if matched is None:
        return None

    canonical = str(matched["canonical_country_region"])
    for idx, label in enumerate(dropdown):
        row = lookup_country(label, aliases)
        if row is not None and str(row["canonical_country_region"]) == canonical:
            return idx
    return None


def mark_dropdown_active() -> None:
    st.session_state["country_source"] = "dropdown"


def mark_manual_active(aliases: pd.DataFrame, dropdown: list[str]) -> None:
    manual_country = st.session_state.get("manual_country", "").strip()
    if not manual_country:
        st.session_state["country_source"] = "dropdown"
        return
    st.session_state["country_source"] = "manual"
    matched_index = find_dropdown_index(manual_country, aliases, dropdown)
    if matched_index is not None:
        st.session_state["selected_country"] = dropdown[matched_index]


def lookup_zone(country_input: str, aliases: pd.DataFrame) -> tuple[str, str]:
    row = lookup_country(country_input, aliases)
    if row is None:
        return "Need Review", "Need Review"
    return str(row["ip_zone"]), str(row["canonical_country_region"])


def lookup_demand(country_input: str, aliases: pd.DataFrame):
    row = lookup_country(country_input, aliases)
    if row is None:
        return "Need Review", None, None
    if row.get("demand_review_status") != "OK":
        return "Need Review", None, None
    return (
        str(row["demand_region_cn"]),
        float(row["demand_rate_cny_per_kg"]),
        float(row["demand_minimum_cny"]),
    )


def calculate_base(weight_kg: float, zone: str, fixed: pd.DataFrame, per_kg: pd.DataFrame):
    if zone == "Need Review":
        return None, "Need Review", None
    if weight_kg <= 20.5:
        lookup_weight = ((weight_kg * 2 + 0.999999) // 1) / 2
        matched = fixed[(fixed["weight_kg"] == lookup_weight) & (fixed["zone"].astype(str) == zone)]
        if matched.empty:
            return None, "Need Review", lookup_weight
        return float(matched.iloc[0]["base_rate_cny"]), "Fixed 0.5-20.5kg", lookup_weight

    matched = per_kg[
        (per_kg["min_kg"] <= weight_kg)
        & (per_kg["max_kg"] >= weight_kg)
        & (per_kg["zone"].astype(str) == zone)
    ]
    if matched.empty:
        return None, "Need Review", weight_kg
    rate = float(matched.iloc[0]["rate_cny_per_kg"])
    return weight_kg * rate, "Per kg 21kg+", weight_kg


def main() -> None:
    st.set_page_config(page_title="FedEx IP 运费核价助手", layout="wide")
    title_col, notice_col, feedback_col = st.columns([7.2, 0.7, 0.7], vertical_alignment="center")
    with title_col:
        st.title("FedEx IP 运费核价助手")
    with notice_col:
        with st.popover("更新通知"):
            st.markdown("5月17日发布第一个版本")
    with feedback_col:
        with st.popover("反馈留言"):
            st.caption("当前本地试算版的反馈不会自动发送。云端版可接入邮箱、企业微信或表单。")
            feedback_text = st.text_area("问题或建议", height=120, placeholder="例如：某个国家匹配不对、某票价格需要复核...")
            if st.button("记录反馈"):
                if feedback_text.strip():
                    st.success("已记录在当前页面会话中。后续可接入邮箱或表单。")
                else:
                    st.warning("请先填写反馈内容。")
    st.caption(
        f"工具版本 {TOOL_VERSION} | IP 协议价 {IP_RATE_EFFECTIVE_DATE} | "
        f"需求附加费 {DEMAND_EFFECTIVE_DATE} | 燃油费 FedEx 48% + 5%冗余 = 53% | "
        f"燃油来源：FedEx 中国燃油附加费页面；当前采用 {FEDEX_FUEL_EFFECTIVE_LABEL} 版本，"
        f"官网 {FEDEX_FUEL_RATE:.0%}，本工具按官网 +5% 冗余计算"
    )
    st.caption(
        "本工具仅用于内部运费快速预估，计算结果不作为最终结算依据；协议价、附加费、汇率及最终报价口径需经相关负责人确认，"
        "实际费用以 FedEx 账单和公司正式报价流程为准。"
    )

    aliases, fixed, per_kg, dropdown = load_data()

    with st.container(border=True):
        st.subheader("输入区")
        col1, col2 = st.columns([2.4, 2.0])
        with col1:
            selected_country = st.selectbox(
                "目的地（下拉）",
                dropdown,
                index=dropdown.index("United States - Other Areas (美国其他地区)")
                if "United States - Other Areas (美国其他地区)" in dropdown
                else 0,
                key="selected_country",
                on_change=mark_dropdown_active,
            )
        with col2:
            manual_country = st.text_input(
                "目的地（手输，可选）",
                value="",
                key="manual_country",
                on_change=mark_manual_active,
                args=(aliases, dropdown),
            )

        col3, col4, col5, col6 = st.columns(4)
        with col3:
            weight_kg = st.number_input("实际重量 kg", min_value=0.5, value=10.0, step=0.5)
        with col4:
            fuel_rate = st.number_input("燃油附加费率（官网+5%）", min_value=0.0, value=DEFAULT_FUEL_RATE, step=0.01, format="%.2f")
        with col5:
            markup = st.number_input("冗余系数", min_value=1.0, value=DEFAULT_MARKUP, step=0.01, format="%.2f")
        with col6:
            exchange_rate = st.number_input("汇率 CNY/USD", min_value=0.01, value=DEFAULT_EXCHANGE_RATE, step=0.01, format="%.2f")

        country_source = st.session_state.get("country_source", "dropdown")
        country_input = manual_country.strip() if country_source == "manual" and manual_country.strip() else selected_country

        zone, matched_country = lookup_zone(country_input, aliases)
        demand_region, demand_rate, demand_minimum = lookup_demand(country_input, aliases)
        base_cny, rate_type, lookup_weight = calculate_base(weight_kg, zone, fixed, per_kg)
        if demand_rate is not None:
            demand_surcharge_cny = max(weight_kg * demand_rate, demand_minimum) if demand_rate > 0 else 0.0
            st.caption(
                f"自动带出：{matched_country} | IP Zone {zone} | "
                f"需求附加费大区 {demand_region} | 需求附加费 {demand_surcharge_cny:,.2f} CNY"
            )

    if base_cny is None or demand_rate is None:
        st.warning("Need Review：国家/地区、重量或旺季附加费区域未匹配。")
        st.stop()

    freight_before_fuel = base_cny + demand_surcharge_cny
    fuel_cny = freight_before_fuel * fuel_rate
    final_cny = (freight_before_fuel + fuel_cny) * markup
    final_usd = final_cny / exchange_rate

    with st.container(border=True):
        st.subheader("报价结果")
        result_cols = st.columns(5)
        result_cols[0].metric("最终 USD", f"{final_usd:,.2f}")
        result_cols[1].metric("最终 CNY", f"{final_cny:,.2f}")
        result_cols[2].metric("基础运费 CNY", f"{base_cny:,.2f}")
        result_cols[3].metric("燃油附加费 CNY", f"{fuel_cny:,.2f}")
        result_cols[4].metric("需求附加费 CNY", f"{demand_surcharge_cny:,.2f}")
        st.caption(
            "报价公式：最终 USD = (基础运费 CNY + 需求附加费 CNY) × "
            "(1 + 燃油附加费率) × 冗余系数 ÷ 汇率"
        )

    with st.container(border=True):
        st.subheader("基础运费计算")
        st.dataframe(
            pd.DataFrame(
                [
                    {
                        "国家/地区": matched_country,
                        "IP 分区": zone,
                        "基础运费算法": rate_type,
                        "查表重量": lookup_weight,
                        "基础运费 CNY": round(base_cny, 2),
                        "需求附加费大区": demand_region,
                        "需求费率 CNY/kg": demand_rate,
                        "最低收费 CNY/票": demand_minimum,
                        "状态": "OK",
                    }
                ]
            ),
            width="stretch",
            hide_index=True,
        )

    st.caption("范围：仅中国大陆 FedEx 国际出口 IP 包裹；不含 IPE、IE、进口、第三方支付、重货、快递封、快递袋、税费、偏远地区附加费和特殊处理费。")


if __name__ == "__main__":
    main()
