"""Streamlit local trial app for the FedEx IP freight checker.

It reuses processed CSV files generated by:
    python3 scripts/01_extract_ip_data.py
"""

from __future__ import annotations

import csv
import uuid
from datetime import datetime
from pathlib import Path

import pandas as pd
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data_processed"
LOG_DIR = PROJECT_ROOT / "logs"
USAGE_LOG = LOG_DIR / "usage_events.csv"
FEEDBACK_LOG = LOG_DIR / "feedback_messages.csv"
USAGE_COLUMNS = [
    "timestamp",
    "session_id",
    "event_type",
    "country_input",
    "matched_country",
    "ip_zone",
    "weight_kg",
    "final_usd",
]
FEEDBACK_COLUMNS = ["message_id", "timestamp", "session_id", "message", "likes", "is_deleted"]

TOOL_VERSION = "2026-05-20"
IP_RATE_EFFECTIVE_DATE = "2026-01-05"
SEASONAL_SURCHARGE_EFFECTIVE_DATE = "2026-04-13"
FEDEX_FUEL_SOURCE_URL = "https://www.fedex.com/zh-cn/shipping/surcharges.html"
FEDEX_FUEL_TABLE_URL = "https://www.fedex.com/content/dam/fedex/international/rates/fedex-fuel-table-may-2026-apac.pdf"
FEDEX_FUEL_EFFECTIVE_LABEL = "2026-04-06 至 2026-05-17"
FEDEX_FUEL_RATE = 0.48
FUEL_BUFFER_RATE = 0.05
DEFAULT_FUEL_RATE = FEDEX_FUEL_RATE + FUEL_BUFFER_RATE
DEFAULT_MARKUP = 1.1
DEFAULT_EXCHANGE_RATE = 6.8


@st.cache_data
def load_data():
    aliases = pd.read_csv(DATA_DIR / "country_alias.csv")
    fixed = pd.read_csv(DATA_DIR / "ip_parcel_rate_0_20_5kg.csv")
    per_kg = pd.read_csv(DATA_DIR / "ip_parcel_rate_21kg_plus.csv")
    dropdown = (
        aliases[aliases["match_note"].eq("Dropdown display label")]["alias"]
        .dropna()
        .drop_duplicates()
        .sort_values(key=lambda s: s.str.lower())
        .tolist()
    )
    return aliases, fixed, per_kg, dropdown


def ensure_session_id() -> str:
    if "session_id" not in st.session_state:
        st.session_state["session_id"] = str(uuid.uuid4())
    return st.session_state["session_id"]


def mark_user_edited_input() -> None:
    st.session_state["has_user_edited_input"] = True


def read_usage_events() -> pd.DataFrame:
    if not USAGE_LOG.exists():
        return pd.DataFrame(columns=USAGE_COLUMNS)

    rows = []
    with USAGE_LOG.open("r", encoding="utf-8-sig", newline="") as file:
        reader = csv.reader(file)
        next(reader, None)
        for values in reader:
            if not values:
                continue
            row = {column: "" for column in USAGE_COLUMNS}
            for index, value in enumerate(values[: len(USAGE_COLUMNS)]):
                row[USAGE_COLUMNS[index]] = value
            rows.append(row)
    return pd.DataFrame(rows, columns=USAGE_COLUMNS)


def log_usage_event(event_type: str, **details: object) -> None:
    LOG_DIR.mkdir(exist_ok=True)
    row = {column: "" for column in USAGE_COLUMNS}
    row.update(
        {
            "timestamp": datetime.now().isoformat(timespec="seconds"),
            "session_id": ensure_session_id(),
            "event_type": event_type,
            **details,
        }
    )
    events = pd.concat([read_usage_events(), pd.DataFrame([row], columns=USAGE_COLUMNS)], ignore_index=True)
    events.to_csv(USAGE_LOG, index=False, encoding="utf-8-sig")


def read_feedback_messages() -> pd.DataFrame:
    if not FEEDBACK_LOG.exists():
        return pd.DataFrame(columns=FEEDBACK_COLUMNS)

    rows = []
    with FEEDBACK_LOG.open("r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)
        for value in reader:
            row = {column: value.get(column, "") for column in FEEDBACK_COLUMNS}
            rows.append(row)
    feedback = pd.DataFrame(rows, columns=FEEDBACK_COLUMNS)
    if not feedback.empty:
        feedback["likes"] = pd.to_numeric(feedback["likes"], errors="coerce").fillna(0).astype(int)
        feedback["is_deleted"] = feedback["is_deleted"].astype(str)
    return feedback


def save_feedback_messages(feedback: pd.DataFrame) -> None:
    LOG_DIR.mkdir(exist_ok=True)
    feedback.to_csv(FEEDBACK_LOG, index=False, encoding="utf-8-sig")


def add_feedback_message(message: str) -> None:
    feedback = read_feedback_messages()
    row = {
        "message_id": str(uuid.uuid4()),
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "session_id": ensure_session_id(),
        "message": message.strip(),
        "likes": 0,
        "is_deleted": "false",
    }
    updated = pd.concat([feedback, pd.DataFrame([row], columns=FEEDBACK_COLUMNS)], ignore_index=True)
    save_feedback_messages(updated)


def like_feedback_message(message_id: str) -> None:
    feedback = read_feedback_messages()
    if feedback.empty:
        return
    liked_key = f"liked_{message_id}"
    if st.session_state.get(liked_key):
        return
    feedback.loc[feedback["message_id"] == message_id, "likes"] = (
        pd.to_numeric(feedback.loc[feedback["message_id"] == message_id, "likes"], errors="coerce").fillna(0).astype(int) + 1
    )
    save_feedback_messages(feedback)
    st.session_state[liked_key] = True


def delete_own_feedback_message(message_id: str) -> None:
    feedback = read_feedback_messages()
    if feedback.empty:
        return
    own_message = (feedback["message_id"] == message_id) & (feedback["session_id"] == ensure_session_id())
    feedback.loc[own_message, "is_deleted"] = "true"
    save_feedback_messages(feedback)


def load_usage_summary() -> tuple[dict[str, int], pd.DataFrame]:
    events = read_usage_events()
    if events.empty:
        return {"unique_sessions": 0, "page_views": 0, "quote_events": 0}, pd.DataFrame()
    summary = {
        "unique_sessions": int(events["session_id"].nunique()) if "session_id" in events else 0,
        "page_views": int((events["event_type"] == "page_view").sum()) if "event_type" in events else 0,
        "quote_events": int((events["event_type"] == "quote").sum()) if "event_type" in events else 0,
    }
    return summary, events.tail(20).sort_index(ascending=False)


def format_recent_usage(recent_events: pd.DataFrame) -> str:
    if recent_events.empty or "event_type" not in recent_events:
        return "最近使用记录：暂无"

    quote_events = recent_events[recent_events["event_type"] == "quote"]
    if quote_events.empty:
        return "最近使用记录：暂无试算"

    latest = quote_events.iloc[0]
    matched_country = latest.get("matched_country", "-")
    weight_kg = latest.get("weight_kg", "-")
    ip_zone = latest.get("ip_zone", "-")
    final_usd = latest.get("final_usd", "-")
    return f"最近试算：{matched_country} / {weight_kg}kg / Zone {ip_zone} / USD {final_usd}"


def lookup_country(country_input: str, aliases: pd.DataFrame):
    key = country_input.strip().lower()
    matched = aliases[aliases["alias_normalized"] == key]
    if matched.empty:
        return None
    return matched.iloc[0]


def find_dropdown_index(country_input: str, aliases: pd.DataFrame, dropdown: list[str]) -> int | None:
    query = country_input.strip().lower()
    if not query:
        return None

    for idx, label in enumerate(dropdown):
        if query in label.lower():
            return idx

    matched = lookup_country(country_input, aliases)
    if matched is None:
        return None

    canonical = str(matched["canonical_country_region"])
    for idx, label in enumerate(dropdown):
        row = lookup_country(label, aliases)
        if row is not None and str(row["canonical_country_region"]) == canonical:
            return idx
    return None


def mark_dropdown_active() -> None:
    mark_user_edited_input()
    st.session_state["country_source"] = "dropdown"


def mark_manual_active(aliases: pd.DataFrame, dropdown: list[str]) -> None:
    mark_user_edited_input()
    manual_country = st.session_state.get("manual_country", "").strip()
    if not manual_country:
        st.session_state["country_source"] = "dropdown"
        return
    st.session_state["country_source"] = "manual"
    matched_index = find_dropdown_index(manual_country, aliases, dropdown)
    if matched_index is not None:
        st.session_state["selected_country"] = dropdown[matched_index]


def lookup_zone(country_input: str, aliases: pd.DataFrame) -> tuple[str, str]:
    row = lookup_country(country_input, aliases)
    if row is None:
        return "Need Review", "Need Review"
    return str(row["ip_zone"]), str(row["canonical_country_region"])


def lookup_demand(country_input: str, aliases: pd.DataFrame):
    row = lookup_country(country_input, aliases)
    if row is None:
        return "Need Review", None, None
    if row.get("demand_review_status") != "OK":
        return "Need Review", None, None
    return (
        str(row["demand_region_cn"]),
        float(row["demand_rate_cny_per_kg"]),
        float(row["demand_minimum_cny"]),
    )


def calculate_base(weight_kg: float, zone: str, fixed: pd.DataFrame, per_kg: pd.DataFrame):
    if zone == "Need Review":
        return None, "Need Review", None
    if weight_kg <= 20.5:
        lookup_weight = ((weight_kg * 2 + 0.999999) // 1) / 2
        matched = fixed[(fixed["weight_kg"] == lookup_weight) & (fixed["zone"].astype(str) == zone)]
        if matched.empty:
            return None, "Need Review", lookup_weight
        return float(matched.iloc[0]["base_rate_cny"]), "Fixed 0.5-20.5kg", lookup_weight

    matched = per_kg[
        (per_kg["min_kg"] <= weight_kg)
        & (per_kg["max_kg"] >= weight_kg)
        & (per_kg["zone"].astype(str) == zone)
    ]
    if matched.empty:
        return None, "Need Review", weight_kg
    rate = float(matched.iloc[0]["rate_cny_per_kg"])
    return weight_kg * rate, "Per kg 21kg+", weight_kg


def main() -> None:
    st.set_page_config(page_title="FedEx IP 运费核价助手", layout="wide")
    session_id = ensure_session_id()
    if not st.session_state.get("page_view_logged"):
        log_usage_event("page_view")
        st.session_state["page_view_logged"] = True

    title_col, notice_col, feedback_col = st.columns([7.2, 0.72, 0.72], vertical_alignment="center")
    with title_col:
        st.title("FedEx IP 运费核价助手")
    with notice_col:
        with st.popover("更新通知"):
            st.markdown("5月20日更新：文案统一为旺季附加费，试算次数改为用户实际修改输入后记录。")
    with feedback_col:
        with st.popover("反馈留言"):
            st.caption("可以直接留言。临时留言保存在当前云端运行环境，长期版后续会接 Google Sheet 或数据库。")
            feedback_text = st.text_area("留言内容", key="feedback_text", height=90, placeholder="例如：某个国家匹配不对、某票价格需要复核...")
            if st.button("发送留言", key="send_feedback"):
                if feedback_text.strip():
                    add_feedback_message(feedback_text)
                    st.success("已发送")
                    st.rerun()
                else:
                    st.warning("请先填写留言内容。")

            feedback = read_feedback_messages()
            active_feedback = feedback[feedback["is_deleted"].ne("true")].tail(5).sort_index(ascending=False)
            if active_feedback.empty:
                st.caption("暂无留言。")
            else:
                st.caption("最近留言")
                for _, message in active_feedback.iterrows():
                    st.markdown(f"**{message['message']}**")
                    st.caption(f"{message['timestamp']} · 点赞 {int(message['likes'])}")
                    button_cols = st.columns([1, 1.6])
                    if button_cols[0].button("点赞", key=f"like_{message['message_id']}"):
                        like_feedback_message(str(message["message_id"]))
                        st.rerun()
                    if message["session_id"] == session_id:
                        if button_cols[1].button("删除自己的留言", key=f"delete_{message['message_id']}"):
                            delete_own_feedback_message(str(message["message_id"]))
                            st.rerun()
    st.caption(
        f"网址版本 {TOOL_VERSION} | IP 协议价 {IP_RATE_EFFECTIVE_DATE} | "
        f"旺季附加费 {SEASONAL_SURCHARGE_EFFECTIVE_DATE} | 燃油费 {FEDEX_FUEL_EFFECTIVE_LABEL} | "
        f"燃油附加费率 FedEx {FEDEX_FUEL_RATE:.0%} + 5%冗余 = {DEFAULT_FUEL_RATE:.0%}"
    )
    st.caption(
        "本工具仅用于内部运费快速预估，计算结果不作为最终结算依据；超过 68kg、偏远地区、特殊处理、税费及其他特殊案例需单独复核，"
        "实际费用以 FedEx 账单和公司正式报价流程为准。"
    )

    aliases, fixed, per_kg, dropdown = load_data()

    with st.container(border=True):
        st.subheader("输入区")
        col1, col2 = st.columns([2.4, 2.0])
        with col1:
            selected_country = st.selectbox(
                "目的地（下拉）",
                dropdown,
                index=dropdown.index("United States - Other Areas (美国其他地区)")
                if "United States - Other Areas (美国其他地区)" in dropdown
                else 0,
                key="selected_country",
                on_change=mark_dropdown_active,
            )
        with col2:
            manual_country = st.text_input(
                "目的地（手输，可选）",
                value="",
                key="manual_country",
                on_change=mark_manual_active,
                args=(aliases, dropdown),
            )

        col3, col4, col5, col6 = st.columns(4)
        with col3:
            weight_kg = st.number_input("实际重量 kg", min_value=0.5, value=10.0, step=0.5, on_change=mark_user_edited_input)
        with col4:
            fuel_rate = st.number_input(
                "燃油附加费率（官网+5%）",
                min_value=0.0,
                value=DEFAULT_FUEL_RATE,
                step=0.01,
                format="%.2f",
                on_change=mark_user_edited_input,
            )
        with col5:
            markup = st.number_input("冗余系数", min_value=1.0, value=DEFAULT_MARKUP, step=0.01, format="%.2f", on_change=mark_user_edited_input)
        with col6:
            exchange_rate = st.number_input(
                "汇率 CNY/USD",
                min_value=0.01,
                value=DEFAULT_EXCHANGE_RATE,
                step=0.01,
                format="%.2f",
                on_change=mark_user_edited_input,
            )

        country_source = st.session_state.get("country_source", "dropdown")
        country_input = manual_country.strip() if country_source == "manual" and manual_country.strip() else selected_country

        zone, matched_country = lookup_zone(country_input, aliases)
        demand_region, demand_rate, demand_minimum = lookup_demand(country_input, aliases)
        base_cny, rate_type, lookup_weight = calculate_base(weight_kg, zone, fixed, per_kg)
        if demand_rate is not None:
            demand_surcharge_cny = max(weight_kg * demand_rate, demand_minimum) if demand_rate > 0 else 0.0
            st.caption(
                f"自动带出：{matched_country} | IP Zone {zone} | "
                f"旺季附加费大区 {demand_region} | 旺季附加费 {demand_surcharge_cny:,.2f} CNY"
            )

    if base_cny is None or demand_rate is None:
        st.warning("Need Review：国家/地区、重量或旺季附加费区域未匹配。")
        st.stop()

    freight_before_fuel = base_cny + demand_surcharge_cny
    fuel_cny = freight_before_fuel * fuel_rate
    final_cny = (freight_before_fuel + fuel_cny) * markup
    final_usd = final_cny / exchange_rate
    quote_signature = f"{session_id}|{country_input}|{weight_kg}|{fuel_rate}|{markup}|{exchange_rate}|{final_usd:.2f}"
    if st.session_state.get("has_user_edited_input") and st.session_state.get("last_quote_signature") != quote_signature:
        log_usage_event(
            "quote",
            country_input=country_input,
            matched_country=matched_country,
            ip_zone=zone,
            weight_kg=weight_kg,
            final_usd=round(final_usd, 2),
        )
        st.session_state["last_quote_signature"] = quote_signature

    with st.container(border=True):
        st.subheader("报价结果")
        result_cols = st.columns(5)
        result_cols[0].metric("最终 USD", f"{final_usd:,.2f}")
        result_cols[1].metric("最终 CNY", f"{final_cny:,.2f}")
        result_cols[2].metric("基础运费 CNY", f"{base_cny:,.2f}")
        result_cols[3].metric("燃油附加费 CNY", f"{fuel_cny:,.2f}")
        result_cols[4].metric("旺季附加费 CNY", f"{demand_surcharge_cny:,.2f}")
        st.caption(
            "报价公式：最终 USD = (基础运费 CNY + 旺季附加费 CNY) × "
            "(1 + 燃油附加费率) × 冗余系数 ÷ 汇率"
        )

    with st.container(border=True):
        st.subheader("基础运费计算")
        base_calc_df = pd.DataFrame(
            [
                {
                    "国家/地区": matched_country,
                    "IP 分区": zone,
                    "基础运费算法": rate_type,
                    "查表重量": lookup_weight,
                    "基础运费 CNY": round(base_cny, 2),
                    "旺季附加费大区": demand_region,
                    "旺季费率 CNY/kg": demand_rate,
                    "最低收费 CNY/票": demand_minimum,
                    "状态": "OK",
                }
            ]
        )
        st.dataframe(
            base_calc_df.style.set_properties(**{"text-align": "left"}).set_table_styles(
                [{"selector": "th", "props": [("text-align", "left")]}]
            ),
            width="stretch",
            hide_index=True,
        )

    st.caption("范围：仅中国大陆 FedEx 国际出口 IP 包裹；不含 IPE、IE、进口、第三方支付、快递封、快递袋、税费、偏远地区附加费和特殊处理费。")
    summary, recent_events = load_usage_summary()
    st.markdown(
        f"""
        <div style="text-align:center; color:#8A8F9C; font-size:12px; margin-top:18px; margin-bottom:6px;">
            总访问次数 {summary["page_views"]} · 试算次数 {summary["quote_events"]} · {format_recent_usage(recent_events)}
        </div>
        """,
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
