"""Streamlit local trial app for the FedEx IP freight checker.

It reuses processed CSV files generated by:
    python3 scripts/01_extract_ip_data.py
"""

from __future__ import annotations

import csv
import json
import uuid
from datetime import datetime
from pathlib import Path

import pandas as pd
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data_processed"
LOG_DIR = PROJECT_ROOT / "logs"
USAGE_LOG = LOG_DIR / "usage_events.csv"
FEEDBACK_LOG = LOG_DIR / "feedback_messages.csv"
RATE_CONFIG = DATA_DIR / "rate_config.json"
USAGE_COLUMNS = [
    "timestamp",
    "session_id",
    "event_type",
    "country_input",
    "matched_country",
    "ip_zone",
    "weight_kg",
    "final_usd",
]
FEEDBACK_COLUMNS = ["message_id", "timestamp", "session_id", "message", "likes", "is_deleted"]

DEFAULT_MARKUP = 1.1
DEFAULT_EXCHANGE_RATE = 6.8


def format_money(value: float, currency: str = "") -> str:
    prefix = f"{currency} " if currency else ""
    return f"{prefix}{value:,.2f}"


def render_v2_styles() -> None:
    st.markdown(
        """
        <style>
            :root {
                --bg: #f6f7fb;
                --panel: #ffffff;
                --ink: #202332;
                --muted: #747b8d;
                --line: #dde2ea;
                --accent: #4f46e5;
                --accent-soft: #eef0ff;
                --ok: #0f8a68;
                --ok-soft: #e8f7f1;
                --warn: #b45309;
            }
            .stApp {
                background:
                    radial-gradient(circle at 10% 0%, rgba(79,70,229,0.08), transparent 26rem),
                    linear-gradient(180deg, #fbfcff 0%, var(--bg) 36rem);
            }
            .block-container {
                padding-top: 1.35rem;
                padding-bottom: 2rem;
                max-width: 1180px;
            }
            h1, h2, h3, p, label, [data-testid="stMarkdownContainer"] {
                font-family: Arial, "Helvetica Neue", sans-serif;
            }
            h1 {
                color: var(--ink);
                letter-spacing: 0;
                font-size: 2.05rem !important;
                line-height: 1.08 !important;
                margin-bottom: 0.2rem !important;
            }
            h2, h3 {
                color: var(--ink);
                letter-spacing: 0;
            }
            div[data-testid="stVerticalBlockBorderWrapper"] {
                border: 1px solid rgba(24, 31, 54, 0.08);
                border-radius: 12px;
                background: rgba(255,255,255,0.88);
                box-shadow: 0 10px 28px rgba(36, 44, 74, 0.055);
            }
            div[data-testid="stMetric"] {
                background: transparent;
            }
            div[data-testid="stMetricValue"] {
                color: var(--ink);
                font-weight: 760;
                letter-spacing: 0;
            }
            .v2-topline {
                display: flex;
                flex-wrap: wrap;
                gap: 8px;
                margin: 10px 0 12px;
                align-items: center;
            }
            .v2-chip {
                display: inline-flex;
                align-items: center;
                gap: 6px;
                padding: 4px 9px;
                border: 1px solid var(--line);
                border-radius: 999px;
                background: rgba(255,255,255,0.86);
                color: #5b6275;
                font-size: 11.5px;
                white-space: nowrap;
            }
            .v2-chip strong {
                color: var(--ink);
                font-weight: 700;
            }
            .v2-note {
                color: var(--muted);
                font-size: 12.5px;
                line-height: 1.6;
                margin: 0 0 14px;
            }
            .v2-result-card {
                border-radius: 14px;
                padding: 22px 22px 18px;
                color: white;
                background:
                    linear-gradient(135deg, rgba(52,50,143,0.98), rgba(18,92,130,0.95)),
                    radial-gradient(circle at 88% 12%, rgba(255,255,255,0.20), transparent 15rem);
                box-shadow: 0 16px 36px rgba(38, 53, 102, 0.18);
                margin-bottom: 14px;
            }
            .v2-result-label {
                font-size: 13px;
                opacity: 0.78;
                margin-bottom: 7px;
            }
            .v2-result-main {
                font-size: 44px;
                font-weight: 780;
                line-height: 1;
                letter-spacing: 0;
                margin-bottom: 8px;
            }
            .v2-result-sub {
                font-size: 14px;
                opacity: 0.84;
            }
            .v2-breakdown {
                display: grid;
                grid-template-columns: repeat(2, minmax(0, 1fr));
                gap: 10px;
                margin-top: 10px;
            }
            .v2-mini-card {
                border: 1px solid rgba(24, 31, 54, 0.08);
                border-radius: 12px;
                background: rgba(255,255,255,0.86);
                padding: 13px 14px;
                min-height: 76px;
            }
            .v2-mini-label {
                color: var(--muted);
                font-size: 12px;
                margin-bottom: 7px;
            }
            .v2-mini-value {
                color: var(--ink);
                font-size: 20px;
                font-weight: 760;
                line-height: 1.15;
            }
            .v2-match-grid {
                display: grid;
                grid-template-columns: repeat(4, minmax(0, 1fr));
                gap: 10px;
                margin: 10px 0 0;
            }
            .v2-match {
                border-radius: 10px;
                border: 1px solid var(--line);
                padding: 10px 12px;
                background: #fbfcff;
            }
            .v2-match-label {
                color: var(--muted);
                font-size: 11px;
                margin-bottom: 5px;
            }
            .v2-match-value {
                color: var(--ink);
                font-weight: 700;
                font-size: 13px;
                line-height: 1.25;
            }
            .v2-formula {
                color: var(--muted);
                font-size: 12px;
                line-height: 1.55;
                padding-top: 4px;
            }
            [data-testid="stSelectbox"] label,
            [data-testid="stTextInput"] label,
            [data-testid="stNumberInput"] label {
                color: var(--ink);
                font-weight: 700;
                font-size: 13px;
            }
            [data-testid="stDataFrame"] {
                border-radius: 10px;
                overflow: hidden;
            }
            div[data-testid="stPopover"] button {
                min-height: 28px;
                padding: 2px 8px;
                border-radius: 8px;
                color: #586073;
                font-size: 10.5px;
                line-height: 1.2;
                box-shadow: none;
                background: rgba(255,255,255,0.72);
            }
            div[data-testid="stPopover"] button p {
                font-size: 10.5px;
                line-height: 1.2;
            }
            [data-testid="stPopoverBody"] p,
            [data-testid="stPopoverBody"] li {
                color: #5d6475;
                font-size: 12.5px;
                line-height: 1.55;
            }
            [data-testid="stPopoverBody"] strong {
                color: #222638;
            }
            @media (max-width: 760px) {
                .block-container { padding-top: 0.8rem; }
                .v2-result-main { font-size: 34px; }
                .v2-breakdown, .v2-match-grid {
                    grid-template-columns: 1fr;
                }
            }
        </style>
        """,
        unsafe_allow_html=True,
    )


@st.cache_data
def load_rate_config() -> dict:
    return json.loads(RATE_CONFIG.read_text(encoding="utf-8"))


@st.cache_data
def load_data():
    aliases = pd.read_csv(DATA_DIR / "country_alias.csv")
    seasonal_rates = pd.read_csv(DATA_DIR / "demand_surcharge_latest.csv")
    seasonal_rate_map = seasonal_rates.set_index("demand_region_code")["priority_rate_cny_per_kg"].to_dict()
    seasonal_min_map = seasonal_rates.set_index("demand_region_code")["minimum_cny_per_shipment"].to_dict()
    aliases["demand_rate_cny_per_kg"] = aliases["demand_region_code"].map(seasonal_rate_map).fillna(aliases["demand_rate_cny_per_kg"])
    aliases["demand_minimum_cny"] = aliases["demand_region_code"].map(seasonal_min_map).fillna(aliases["demand_minimum_cny"])
    fixed = pd.read_csv(DATA_DIR / "ip_parcel_rate_0_20_5kg.csv")
    per_kg = pd.read_csv(DATA_DIR / "ip_parcel_rate_21kg_plus.csv")
    dropdown = (
        aliases[aliases["match_note"].eq("Dropdown display label")]["alias"]
        .dropna()
        .drop_duplicates()
        .sort_values(key=lambda s: s.str.lower())
        .tolist()
    )
    return aliases, fixed, per_kg, dropdown


def ensure_session_id() -> str:
    if "session_id" not in st.session_state:
        st.session_state["session_id"] = str(uuid.uuid4())
    return st.session_state["session_id"]


def is_admin() -> bool:
    admin_key = st.secrets.get("admin_delete_key", "") if hasattr(st, "secrets") else ""
    entered_key = st.session_state.get("admin_delete_key", "")
    return bool(admin_key and entered_key == admin_key)


def mark_user_edited_input() -> None:
    st.session_state["has_user_edited_input"] = True


@st.cache_data(ttl=5)
def read_usage_events() -> pd.DataFrame:
    if not USAGE_LOG.exists():
        return pd.DataFrame(columns=USAGE_COLUMNS)
    return pd.read_csv(USAGE_LOG, dtype=str).fillna("")


def log_usage_event(event_type: str, **details: object) -> None:
    LOG_DIR.mkdir(exist_ok=True)
    row = {column: "" for column in USAGE_COLUMNS}
    row.update(
        {
            "timestamp": datetime.now().isoformat(timespec="seconds"),
            "session_id": ensure_session_id(),
            "event_type": event_type,
            **details,
        }
    )
    write_header = not USAGE_LOG.exists()
    with USAGE_LOG.open("a", encoding="utf-8-sig", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=USAGE_COLUMNS)
        if write_header:
            writer.writeheader()
        writer.writerow(row)


@st.cache_data(ttl=2)
def read_feedback_messages() -> pd.DataFrame:
    if not FEEDBACK_LOG.exists():
        return pd.DataFrame(columns=FEEDBACK_COLUMNS)
    feedback = pd.read_csv(FEEDBACK_LOG, dtype=str).fillna("")
    if not feedback.empty:
        feedback["likes"] = pd.to_numeric(feedback["likes"], errors="coerce").fillna(0).astype(int)
        feedback["is_deleted"] = feedback["is_deleted"].astype(str)
    return feedback


def save_feedback_messages(feedback: pd.DataFrame) -> None:
    LOG_DIR.mkdir(exist_ok=True)
    feedback.to_csv(FEEDBACK_LOG, index=False, encoding="utf-8-sig")


def add_feedback_message(message: str) -> None:
    feedback = read_feedback_messages()
    row = {
        "message_id": str(uuid.uuid4()),
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "session_id": ensure_session_id(),
        "message": message.strip(),
        "likes": 0,
        "is_deleted": "false",
    }
    updated = pd.concat([feedback, pd.DataFrame([row], columns=FEEDBACK_COLUMNS)], ignore_index=True)
    save_feedback_messages(updated)


def like_feedback_message(message_id: str) -> None:
    feedback = read_feedback_messages()
    if feedback.empty:
        return
    liked_key = f"liked_{message_id}"
    if st.session_state.get(liked_key):
        return
    feedback.loc[feedback["message_id"] == message_id, "likes"] = (
        pd.to_numeric(feedback.loc[feedback["message_id"] == message_id, "likes"], errors="coerce").fillna(0).astype(int) + 1
    )
    save_feedback_messages(feedback)
    st.session_state[liked_key] = True


def delete_feedback_message(message_id: str) -> None:
    feedback = read_feedback_messages()
    if feedback.empty:
        return
    allowed = (feedback["message_id"] == message_id) & (
        (feedback["session_id"] == ensure_session_id()) | is_admin()
    )
    feedback.loc[allowed, "is_deleted"] = "true"
    save_feedback_messages(feedback)


def load_usage_summary() -> tuple[dict[str, int], pd.DataFrame]:
    events = read_usage_events()
    if events.empty:
        return {"unique_sessions": 0, "page_views": 0, "quote_events": 0}, pd.DataFrame()
    summary = {
        "unique_sessions": int(events["session_id"].nunique()) if "session_id" in events else 0,
        "page_views": int((events["event_type"] == "page_view").sum()) if "event_type" in events else 0,
        "quote_events": int((events["event_type"] == "quote").sum()) if "event_type" in events else 0,
    }
    return summary, events.tail(20).sort_index(ascending=False)


def format_recent_usage(recent_events: pd.DataFrame) -> str:
    if recent_events.empty or "event_type" not in recent_events:
        return "最近使用记录：暂无"

    quote_events = recent_events[recent_events["event_type"] == "quote"]
    if quote_events.empty:
        return "最近使用记录：暂无试算"

    latest = quote_events.iloc[0]
    matched_country = latest.get("matched_country", "-")
    weight_kg = latest.get("weight_kg", "-")
    ip_zone = latest.get("ip_zone", "-")
    final_usd = latest.get("final_usd", "-")
    return f"最近试算：{matched_country} / {weight_kg}kg / Zone {ip_zone} / USD {final_usd}"


def lookup_country(country_input: str, aliases: pd.DataFrame):
    key = country_input.strip().lower()
    matched = aliases[aliases["alias_normalized"] == key]
    if matched.empty:
        return None
    return matched.iloc[0]


def find_dropdown_index(country_input: str, aliases: pd.DataFrame, dropdown: list[str]) -> int | None:
    query = country_input.strip().lower()
    if not query:
        return None

    for idx, label in enumerate(dropdown):
        if query in label.lower():
            return idx

    matched = lookup_country(country_input, aliases)
    if matched is None:
        return None

    canonical = str(matched["canonical_country_region"])
    for idx, label in enumerate(dropdown):
        row = lookup_country(label, aliases)
        if row is not None and str(row["canonical_country_region"]) == canonical:
            return idx
    return None


def mark_dropdown_active() -> None:
    mark_user_edited_input()
    st.session_state["country_source"] = "dropdown"


def mark_manual_active(aliases: pd.DataFrame, dropdown: list[str]) -> None:
    mark_user_edited_input()
    manual_country = st.session_state.get("manual_country", "").strip()
    if not manual_country:
        st.session_state["country_source"] = "dropdown"
        return
    st.session_state["country_source"] = "manual"
    matched_index = find_dropdown_index(manual_country, aliases, dropdown)
    if matched_index is not None:
        st.session_state["selected_country"] = dropdown[matched_index]


def lookup_zone(country_input: str, aliases: pd.DataFrame) -> tuple[str, str]:
    row = lookup_country(country_input, aliases)
    if row is None:
        return "Need Review", "Need Review"
    return str(row["ip_zone"]), str(row["canonical_country_region"])


def lookup_demand(country_input: str, aliases: pd.DataFrame):
    row = lookup_country(country_input, aliases)
    if row is None:
        return "Need Review", None, None
    if row.get("demand_review_status") != "OK":
        return "Need Review", None, None
    return (
        str(row["demand_region_cn"]),
        float(row["demand_rate_cny_per_kg"]),
        float(row["demand_minimum_cny"]),
    )


def calculate_base(weight_kg: float, zone: str, fixed: pd.DataFrame, per_kg: pd.DataFrame):
    if zone == "Need Review":
        return None, "Need Review", None
    if weight_kg <= 20.5:
        lookup_weight = ((weight_kg * 2 + 0.999999) // 1) / 2
        matched = fixed[(fixed["weight_kg"] == lookup_weight) & (fixed["zone"].astype(str) == zone)]
        if matched.empty:
            return None, "Need Review", lookup_weight
        return float(matched.iloc[0]["base_rate_cny"]), "Fixed 0.5-20.5kg", lookup_weight

    matched = per_kg[
        (per_kg["min_kg"] <= weight_kg)
        & (per_kg["max_kg"] >= weight_kg)
        & (per_kg["zone"].astype(str) == zone)
    ]
    if matched.empty:
        return None, "Need Review", weight_kg
    rate = float(matched.iloc[0]["rate_cny_per_kg"])
    return weight_kg * rate, "Per kg 21kg+", weight_kg


def main() -> None:
    st.set_page_config(page_title="FedEx IP 运费核价助手", layout="wide")
    rate_config = load_rate_config()
    render_v2_styles()
    session_id = ensure_session_id()
    if not st.session_state.get("page_view_logged"):
        log_usage_event("page_view")
        st.session_state["page_view_logged"] = True

    title_col, notice_col, feedback_col = st.columns([7.2, 0.82, 0.82], vertical_alignment="center")
    with title_col:
        st.title("FedEx IP 运费核价助手 2.0")
    with notice_col:
        with st.popover("更新通知"):
            st.markdown(
                """
                - **V1.0 · 2026-05-17**：上线 IP 包裹核价，确认国家分区、0.5-20.5kg 固定价和 21kg+ 每公斤价。
                - **V1.1 · 2026-05-20**：加入旺季附加费、燃油费配置化、Telegram 检查和 GitHub 自动更新链路。
                - **V2.0 · 2026-05-24**：重做报价台界面，突出最终 USD、费用拆分、IP 分区和旺季大区。
                """
            )
    with feedback_col:
        with st.popover("反馈留言"):
            st.caption("可以直接留言。")
            feedback_text = st.text_area("留言内容", key="feedback_text", height=90, placeholder="例如：某个国家匹配不对、某票价格需要复核...")
            if st.button("发送留言", key="send_feedback"):
                if feedback_text.strip():
                    add_feedback_message(feedback_text)
                    st.success("已发送")
                    st.rerun()
                else:
                    st.warning("请先填写留言内容。")

            feedback = read_feedback_messages()
            active_feedback = feedback[feedback["is_deleted"].ne("true")].tail(5).sort_index(ascending=False)
            if active_feedback.empty:
                st.caption("暂无留言。")
            else:
                st.caption("最近留言")
                for _, message in active_feedback.iterrows():
                    st.markdown(f"**{message['message']}**")
                    st.caption(f"{message['timestamp']} · 点赞 {int(message['likes'])}")
                    button_cols = st.columns([1, 1.6])
                    if button_cols[0].button("点赞", key=f"like_{message['message_id']}"):
                        like_feedback_message(str(message["message_id"]))
                        st.rerun()
                    can_delete = message["session_id"] == session_id or is_admin()
                    if can_delete and button_cols[1].button("删除", key=f"delete_{message['message_id']}"):
                        delete_feedback_message(str(message["message_id"]))
                        st.rerun()
    st.markdown(
        f"""
        <div class="v2-topline">
            <span class="v2-chip">网址版本 <strong>{rate_config['web_version']}</strong></span>
            <span class="v2-chip">IP 协议价 <strong>{rate_config['ip_rate_effective_date']}</strong></span>
            <span class="v2-chip">旺季附加费 <strong>{rate_config['seasonal_surcharge_effective_date']}</strong></span>
            <span class="v2-chip">燃油费 <strong>{rate_config['fuel_effective_label']}</strong></span>
            <span class="v2-chip">FedEx <strong>{rate_config['fedex_fuel_rate']:.2%}</strong> + 冗余 = <strong>{rate_config['default_fuel_rate']:.2%}</strong></span>
        </div>
        <p class="v2-note">
            本工具仅用于内部运费快速预估，计算结果不作为最终结算依据；超过 68kg、偏远地区、特殊处理、税费及其他特殊案例需单独复核，实际费用以 FedEx 账单和公司正式报价流程为准。
        </p>
        """,
        unsafe_allow_html=True,
    )

    aliases, fixed, per_kg, dropdown = load_data()

    work_col, result_col = st.columns([1.06, 0.94], gap="large")
    with work_col:
        with st.container(border=True):
            st.subheader("输入区")
            selected_country = st.selectbox(
                "目的地（下拉）",
                dropdown,
                index=dropdown.index("United States - Other Areas (美国其他地区)")
                if "United States - Other Areas (美国其他地区)" in dropdown
                else 0,
                key="selected_country",
                on_change=mark_dropdown_active,
            )
            manual_country = st.text_input(
                "目的地（手输，可选）",
                value="",
                key="manual_country",
                on_change=mark_manual_active,
                args=(aliases, dropdown),
            )

            col3, col4 = st.columns(2)
            with col3:
                weight_kg = st.number_input("实际重量 kg", min_value=0.5, value=10.0, step=0.5, on_change=mark_user_edited_input)
            with col4:
                fuel_rate = st.number_input(
                    "燃油附加费率（官网+5%）",
                    min_value=0.0,
                    value=float(rate_config["default_fuel_rate"]),
                    step=0.01,
                    format="%.2f",
                    on_change=mark_user_edited_input,
                )
            col5, col6 = st.columns(2)
            with col5:
                markup = st.number_input("冗余系数", min_value=1.0, value=DEFAULT_MARKUP, step=0.01, format="%.2f", on_change=mark_user_edited_input)
            with col6:
                exchange_rate = st.number_input(
                    "汇率 CNY/USD",
                    min_value=0.01,
                    value=DEFAULT_EXCHANGE_RATE,
                    step=0.01,
                    format="%.2f",
                    on_change=mark_user_edited_input,
                )

            country_source = st.session_state.get("country_source", "dropdown")
            country_input = manual_country.strip() if country_source == "manual" and manual_country.strip() else selected_country

            zone, matched_country = lookup_zone(country_input, aliases)
            demand_region, demand_rate, demand_minimum = lookup_demand(country_input, aliases)
            base_cny, rate_type, lookup_weight = calculate_base(weight_kg, zone, fixed, per_kg)
            if demand_rate is not None:
                demand_surcharge_cny = max(weight_kg * demand_rate, demand_minimum) if demand_rate > 0 else 0.0

    if base_cny is None or demand_rate is None:
        st.warning("Need Review：国家/地区、重量或旺季附加费区域未匹配。")
        st.stop()

    freight_before_fuel = base_cny + demand_surcharge_cny
    fuel_cny = freight_before_fuel * fuel_rate
    final_cny = (freight_before_fuel + fuel_cny) * markup
    final_usd = final_cny / exchange_rate
    quote_signature = f"{session_id}|{country_input}|{weight_kg}|{fuel_rate}|{markup}|{exchange_rate}|{final_usd:.2f}"
    if st.session_state.get("has_user_edited_input") and st.session_state.get("last_quote_signature") != quote_signature:
        log_usage_event(
            "quote",
            country_input=country_input,
            matched_country=matched_country,
            ip_zone=zone,
            weight_kg=weight_kg,
            final_usd=round(final_usd, 2),
        )
        st.session_state["last_quote_signature"] = quote_signature

    with result_col:
        st.markdown(
            f"""
            <div class="v2-result-card">
                <div class="v2-result-label">最终报价 USD</div>
                <div class="v2-result-main">{final_usd:,.2f}</div>
                <div class="v2-result-sub">最终 CNY {final_cny:,.2f} · {matched_country} · IP Zone {zone}</div>
            </div>
            <div class="v2-breakdown">
                <div class="v2-mini-card"><div class="v2-mini-label">基础运费 CNY</div><div class="v2-mini-value">{format_money(base_cny)}</div></div>
                <div class="v2-mini-card"><div class="v2-mini-label">燃油附加费 CNY</div><div class="v2-mini-value">{format_money(fuel_cny)}</div></div>
                <div class="v2-mini-card"><div class="v2-mini-label">旺季附加费 CNY</div><div class="v2-mini-value">{format_money(demand_surcharge_cny)}</div></div>
                <div class="v2-mini-card"><div class="v2-mini-label">计费口径</div><div class="v2-mini-value">{rate_type}</div></div>
            </div>
            <div class="v2-match-grid">
                <div class="v2-match"><div class="v2-match-label">国家/地区</div><div class="v2-match-value">{matched_country}</div></div>
                <div class="v2-match"><div class="v2-match-label">IP 分区</div><div class="v2-match-value">{zone}</div></div>
                <div class="v2-match"><div class="v2-match-label">旺季大区</div><div class="v2-match-value">{demand_region}</div></div>
                <div class="v2-match"><div class="v2-match-label">查表重量</div><div class="v2-match-value">{lookup_weight:.2f} kg</div></div>
            </div>
            <div class="v2-formula">
                最终 USD = (基础运费 CNY + 旺季附加费 CNY) × (1 + 燃油附加费率) × 冗余系数 ÷ 汇率
            </div>
            """,
            unsafe_allow_html=True,
        )

    with st.container(border=True):
        st.subheader("基础运费计算")
        base_calc_df = pd.DataFrame(
            [
                {
                    "国家/地区": matched_country,
                    "IP 分区": zone,
                    "基础运费算法": rate_type,
                    "查表重量 kg": f"{lookup_weight:.2f}" if lookup_weight is not None else "",
                    "基础运费 CNY": f"{base_cny:.2f}",
                    "旺季附加费大区": demand_region,
                    "旺季费率 CNY/kg": f"{demand_rate:.2f}",
                    "最低收费 CNY/票": f"{demand_minimum:.2f}",
                    "状态": "OK",
                }
            ]
        )
        st.dataframe(
            base_calc_df.style.set_properties(**{"text-align": "left"}).set_table_styles(
                [{"selector": "th", "props": [("text-align", "left")]}]
            ),
            width="stretch",
            hide_index=True,
        )

    st.caption("范围：仅中国大陆 FedEx 国际出口 IP 包裹；不含 IPE、IE、进口、第三方支付、快递封、快递袋、税费、偏远地区附加费和特殊处理费。")
    summary, recent_events = load_usage_summary()
    st.markdown(
        f"""
        <div style="text-align:center; color:#8A8F9C; font-size:12px; margin-top:18px; margin-bottom:6px;">
            总访问次数 {summary["page_views"]} · 试算次数 {summary["quote_events"]} · {format_recent_usage(recent_events)}
        </div>
        """,
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
